directories = ["testdiamond"]
sampleids = ["SRR9641933"]
lanes = [1,2]
"""
def get_forward_paths(directory):
    contents = os.listdir(directory)
    # SRA gives in format of Project/Sample/Sample_1.fastq and Project/Sample/Sample_2.fastq
    # for forward and reverse reads, respectively
    forward_paths = [os.path.join(directory, content, content+"_1.fastq") for content in contents]
    return forward_paths


def get_reverse_paths(directory):

    contents = os.listdir(directory)
    
    reverse_paths = [os.path.join(directory, content, content+"_2.fastq")) for content in contents]
    return reverse_paths
"""
rule all:
    input: 
        "../testdiamond/SRR9641933/SRR9641933.assembled.fastq",
        "../testdiamond/SRR9641933/SRR9641933.discarded.fastq",
        "../testdiamond/SRR9641933/SRR9641933.unassembled.forward.fastq",
        "../testdiamond/SRR9641933/SRR9641933.unassembled.reverse.fastq",
        "../testdiamond/SRR9641933/diamond_results_SRR941933.txt"

"""
    input:
        expand("../{directory}/{sample}/whatthisdid.txt", 
        directory=directories,
        sample=sampleids, 
        lane=lanes)
"""
rule merge_reads:
    input:
        "../testdiamond/SRR9641933/SRR9641933_1.fastq",
        "../testdiamond/SRR9641933/SRR9641933_2.fastq",
    output:
        "../testdiamond/SRR9641933/SRR9641933.assembled.fastq",
        "../testdiamond/SRR9641933/SRR9641933.discarded.fastq",
        "../testdiamond/SRR9641933/SRR9641933.unassembled.forward.fastq",
        "../testdiamond/SRR9641933/SRR9641933.unassembled.reverse.fastq"
    shell:
        " ~/tools/pear/src/pear -f ../testdiamond/SRR9641933/SRR9641933_1.fastq -r ../testdiamond/SRR9641933/SRR9641933_2.fastq -o ../testdiamond/SRR9641933/SRR9641933"

rule run_diamond:
    input:
        "../testdiamond/SRR9641933/SRR9641933.assembled.fastq"
    output:
        "../testdiamond/SRR9641933/diamond_results_SRR941933.txt"
    shell:
        "diamond blastx --db ../database-building/uniprot-nicotine-db.dmnd -q ../testdiamond/SRR9641933/SRR9641933.assembled.fastq > ../testdiamond/SRR9641933/diamond_results_SRR941933.txt" 