directories = ["testdiamond"]
sampleids = ["SRR9641933"]
lanes = [1,2]

project_ids = ["PRJNA548383"]
acc_ids = []

for project in project_ids:
    with open("../"+project+"_Acc_List.txt", "r") as f:
        acc_ids += [line.strip() for line in f.readlines()]

rule all:
    input: 
        expand("../testdiamond/{sampleid}/{sampleid}.assembled.fastq", sampleid=sampleids),
        expand("../testdiamond/{sampleid}/{sampleid}.discarded.fastq", sampleid=sampleids),
        expand("../testdiamond/{sampleid}/{sampleid}.unassembled.forward.fastq", sampleid=sampleids),
        expand("../testdiamond/{sampleid}/{sampleid}.unassembled.reverse.fastq", sampleid=sampleids),

        expand("../testdiamond/{sampleid}/diamond_results_{sampleid}.txt", sampleid=sampleids)

"""
rule all_NOTYET:
    input:
        # get_data grabs the forward and reverse reads
        expand("../data/{sampleid}/{sampleid}_1.fastq",
        sampleid=acc_ids),
        expand("../data/{sampleid}/{sampleid}_2.fastq",
        sampleid=acc_ids),
        # get_data grabs the .sra file as well
        expand("../data/{sampleid}/{sampleid}/{sampleid}.sra",
        sampleid=acc_ids),

        # merge_reads creates these
        expand("../data/{sampleid}/{sampleid}.assembled.fastq",
        sampleid=acc_ids),
        expand("../data/{sampleid}/{sampleid}.discarded.fastq",
        sampleid=acc_ids),
        expand("../data/{sampleid}/{sampleid}.unassembled.forward.fastq",
        sampleid=acc_ids),
        expand("../data/{sampleid}/{sampleid}.unassembled.reverse.fastq",
        sampleid=acc_ids),

        #diamond creates a results file
        expand("../data/{sampleid}/diamond_results_{sampleid}.txt",
        sampleid=acc_ids)


rule get_data:
    output:
        expand("../data/{sampleid}/{sampleid}_1.fastq",
        sampleid=acc_ids),
        expand("../data/{sampleid}/{sampleid}_2.fastq",
        sampleid=acc_ids),
        expand("../data/{sampleid}/{sampleid}/{sampleid}.sra",
        sampleid=acc_ids)
    run:
        commands = [
        "prefetch {wildcards.sampleid} -output-directory ../data/{wildcards.sampleid}", 
        "fasterq-dump {wildcards.sampleid} --outdir ../data/{wildcards.sampleid} --progress"
        ]

        for c in commands:
            shell(c)
"""

rule merge_reads:
    input:
        "../testdiamond/{sampleid}/{sampleid}_1.fastq",
        "../testdiamond/{sampleid}/{sampleid}_2.fastq",
    output:
        "../testdiamond/{sampleid}/{sampleid}.assembled.fastq",
        "../testdiamond/{sampleid}/{sampleid}.discarded.fastq",
        "../testdiamond/{sampleid}/{sampleid}.unassembled.forward.fastq",
        "../testdiamond/{sampleid}/{sampleid}.unassembled.reverse.fastq"
    shell:
        " ~/tools/pear/src/pear -f ../testdiamond/{wildcards.sampleid}/{wildcards.sampleid}_1.fastq -r ../testdiamond/{wildcards.sampleid}/{wildcards.sampleid}_2.fastq -o ../testdiamond/{wildcards.sampleid}/{wildcards.sampleid}"

rule run_diamond:
    input:
        "../testdiamond/{sampleid}/{sampleid}.assembled.fastq"
    output:
        "../testdiamond/{sampleid}/diamond_results_{sampleid}.txt"
    shell:
        "diamond blastx --db ../database-building/uniprot-nicotine-db.dmnd -q ../testdiamond/{wildcards.sampleid}/{wildcards.sampleid}.assembled.fastq > ../testdiamond/{wildcards.sampleid}/diamond_results_{wildcards.sampleid}.txt" 