directories = ["testdiamond"]
sampleids = ["SRR9641933"]
lanes = [1,2]

project_ids = ["PRJNA548383", "PRJNA544061", "PRJNA508385"]
acc_ids = []

for project in project_ids:
    with open("../Accession_lists/"+project+"_Acc_List.txt", "r") as f:
        acc_ids += [line.strip() for line in f.readlines()]

"""
rule all: #for testing
    input: 
        expand("../testdiamond/{sampleid}/{sampleid}.assembled.fastq", sampleid=sampleids),
        expand("../testdiamond/{sampleid}/{sampleid}.discarded.fastq", sampleid=sampleids),
        expand("../testdiamond/{sampleid}/{sampleid}.unassembled.forward.fastq", sampleid=sampleids),
        expand("../testdiamond/{sampleid}/{sampleid}.unassembled.reverse.fastq", sampleid=sampleids),

        expand("../testdiamond/{sampleid}/diamond_results_{sampleid}.txt", sampleid=sampleids)

"""
rule all: #for fiji
    input:
        """
        # get_data grabs the forward and reverse reads
        expand("../data/{sampleid}/{sampleid}_1.fastq",
        sampleid=acc_ids),
        expand("../data/{sampleid}/{sampleid}_2.fastq",
        sampleid=acc_ids),
        # get_data grabs the .sra file as well
        expand("../data/{sampleid}/{sampleid}/{sampleid}.sra",
        sampleid=acc_ids),
        """
        # merge_reads creates these
        expand("../data/{sampleid}/{sampleid}.assembled.fastq",
        sampleid=acc_ids),
        expand("../data/{sampleid}/{sampleid}.discarded.fastq",
        sampleid=acc_ids),
        expand("../data/{sampleid}/{sampleid}.unassembled.forward.fastq",
        sampleid=acc_ids),
        expand("../data/{sampleid}/{sampleid}.unassembled.reverse.fastq",
        sampleid=acc_ids),

        #diamond creates a results file
        expand("../data/{sampleid}/diamond_results_{sampleid}.txt",
        sampleid=acc_ids)

"""
rule get_data:
    output:
        "../data/{sampleid}/{sampleid}_1.fastq",
        "../data/{sampleid}/{sampleid}_2.fastq",
        "../data/{sampleid}/{sampleid}/{sampleid}.sra",
    run:
        commands = [
        "prefetch {wildcards.sampleid} -output-directory ../data/{wildcards.sampleid}", 
        "fasterq-dump {wildcards.sampleid} --outdir ../data/{wildcards.sampleid} --progress"
        ]

        for c in commands:
            shell(c)
"""

rule merge_reads:
    threads: 20
    input:
        "../data/{sampleid}/{sampleid}_1.fastq",
        "../data/{sampleid}/{sampleid}_2.fastq"
    output:
        "../data/{sampleid}/{sampleid}.assembled.fastq",
        "../data/{sampleid}/{sampleid}.discarded.fastq",
        "../data/{sampleid}/{sampleid}.unassembled.forward.fastq",
        "../data/{sampleid}/{sampleid}.unassembled.reverse.fastq"
    shell:
        """ 
        pear -f ../data/{wildcards.sampleid}/{wildcards.sampleid}_1.fastq \
        -r ../data/{wildcards.sampleid}/{wildcards.sampleid}_2.fastq \
        -o ../data/{wildcards.sampleid}/{wildcards.sampleid} \
        --threads 20
        """

rule run_diamond:
    threads: 20
    input:
        "../data/{sampleid}/{sampleid}.assembled.fastq"
    output:
        "../data/{sampleid}/diamond_results_{sampleid}.txt"
    shell:
        """
        diamond blastx --db ../database-building/uniprot-nicotine-db.dmnd \
        -q ../data/{wildcards.sampleid}/{wildcards.sampleid}.assembled.fastq \
        --threads 20 > ../data/{wildcards.sampleid}/diamond_results_{wildcards.sampleid}.txt
        """ 